import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';
import {AtomicJsonStore} from '../src/durable_state.mjs';import {CoordinateDirectory} from '../src/coordinate_directory.mjs';import {Layer2Reconciler} from '../src/layer2_reconciler.mjs';
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'kex-r03-stress-'));
async function workers(file,n=10,count=100){const script=new URL('./atomic_worker.mjs',import.meta.url).pathname;await Promise.all(Array.from({length:n},()=>new Promise((res,rej)=>{const cp=spawn(process.execPath,[script,file,String(count)],{stdio:'ignore'});cp.on('exit',c=>c===0?res():rej(new Error('worker '+c)));cp.on('error',rej)})))}
const root=tmp();const counter=path.join(root,'counter.json');await workers(counter,10,100);const count=new AtomicJsonStore(counter,()=>({count:0})).read().count;if(count!==1000)throw new Error('COUNTER_MISMATCH:'+count);
const secrets={A:'a',B:'b'};const a=new CoordinateDirectory({writerId:'A',writerSecret:'a',writerSecrets:secrets}),b=new CoordinateDirectory({writerId:'B',writerSecret:'b',writerSecrets:secrets});
for(let i=1;i<=100;i++){a.upsert({node_id:'N'+i,health:'READY',logical:`X${i}/Y${i}`});b.upsert({node_id:'N'+i,health:'FAILED',logical:`X${i}/Y${i}`})}
let conflict=false;try{a.merge(b.snapshot())}catch(e){if(String(e.message).includes('CONCURRENT_CONFLICT'))conflict=true;else throw e}if(!conflict)throw new Error('CONFLICT_NOT_DETECTED');
const conflicts=a.conflicts();if(Object.keys(conflicts).length!==100)throw new Error('CONFLICT_COUNT:'+Object.keys(conflicts).length);for(const [id,c] of Object.entries(conflicts))a.resolveConflict(id,c.remote_record.record_hash);if(Object.keys(a.conflicts()).length!==0)throw new Error('CONFLICTS_REMAIN');
const l2state=path.join(root,'l2.json');let world={};const adapter={read:async id=>world[id]||null,apply:async op=>(world[op.node.node_id]={...op.node})};for(let g=1;g<=100;g++){const r=new Layer2Reconciler({statePath:l2state});const desired=[{node_id:'N1',generation_value:g}];const observed=world.N1?[world.N1]:[];const out=await r.apply(r.plan(desired,observed,{generation:g}),adapter);if(out.summary.applied_verified!==1)throw new Error('L2_GENERATION_'+g)}
const stale=new Layer2Reconciler({statePath:l2state});let staleRejected=false;try{await stale.apply(stale.plan([{node_id:'N1',generation_value:99}],[world.N1],{generation:99}),adapter)}catch(e){staleRejected=String(e.message).includes('STALE_GENERATION')}if(!staleRejected)throw new Error('STALE_NOT_REJECTED');
console.log(JSON.stringify({status:'PASS',atomic_increments:count,coordinate_conflicts_resolved:100,l2_generations_applied:100,stale_generation_rejected:true},null,2));
